import "./globals.css";
import { Navbar } from "./components/StyledNavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavStyle = {
  bgColor: "#A52A2A",
  textColor: "#FFE4C4",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Navbar style={NavStyle}></Navbar>
        {children}
      </body>
    </html>
  );
}
